"""empty message

Revision ID: 5412db91597f
Revises: 357013d1c724
Create Date: 2021-01-27 20:33:30.024893

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5412db91597f'
down_revision = '357013d1c724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conta', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nome', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('dataNasc', sa.Date(), nullable=True),
                    sa.Column('senha', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'))
    op.create_table('filme', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('contaId', sa.String(), nullable=True),
                    sa.Column('perfilId', sa.String(), nullable=True),
                    sa.Column('filmeId', sa.Text(), nullable=True),
                    sa.Column('filmeNome', sa.Text(), nullable=True),
                    sa.Column('media', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('perfis', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('conta', sa.Integer(), nullable=True),
                    sa.Column('nome', sa.String(), nullable=True),
                    sa.Column('filmes', sa.PickleType(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['conta'],
                        ['conta.id'],
                    ), sa.ForeignKeyConstraint(
                        ['filmes'],
                        ['filme.id'],
                    ), sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perfis')
    op.drop_table('filme')
    op.drop_table('conta')
    # ### end Alembic commands ###
